"""
Shared functions for loading new gene dependency data and getting it ready
to run through the trained BioBombe ensemble.

Every function here works off two building blocks from the existing pipeline:
- 0.data-download/data/CRISPRGeneEffect.csv, the original DepMap data the
  ensemble was trained on
- 0.data-download/data/CRISPR_gene_dictionary.parquet, the QC dictionary that
  determines exactly which genes, and in what order, the trained models expect

New data is not guaranteed to use the same gene identifiers, cover the same
genes, or list them in the same order as DepMap, so every alignment step here
is explicit and reports what it did rather than silently reindexing.
"""

import pathlib
import re

import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


def _entrez_from_depmap_column(column_name):
    """
    Extract the entrez id from a DepMap-style "SYMBOL (ENTREZID)" column name.
    Returns None if the column doesn't match that pattern.
    """
    match = re.match(r"^.*\((\d+)\)\s*$", str(column_name).strip())
    return match.group(1) if match else None


def load_depmap_reference(data_directory):
    """
    Load the original DepMap gene effect data and QC-passed gene dictionary.

    Parameters
    ----------
    data_directory : str or pathlib.Path
        Path to 0.data-download/data.

    Returns
    -------
    depmap_df : pd.DataFrame
        The original CRISPRGeneEffect.csv, unmodified (ModelID + all genes).
    gene_dict_df : pd.DataFrame
        The full gene dictionary (entrez_id, symbol_id, dependency_column,
        qc_pass_pan, qc_pass_other, qc_pass), not filtered to QC-passed only.
    """
    data_directory = pathlib.Path(data_directory)
    depmap_df = pd.read_csv(data_directory / "CRISPRGeneEffect.csv")
    gene_dict_df = pd.read_parquet(data_directory / "CRISPR_gene_dictionary.parquet")
    gene_dict_df["entrez_id"] = gene_dict_df["entrez_id"].astype(str)
    return depmap_df, gene_dict_df


def get_trained_gene_order(model_save_dir):
    """
    Return the exact, ordered list of genes the BioBombe ensemble (module 3)
    was trained on.

    This reads a static file, 3.run-biobombe/data/trained_gene_order.parquet,
    generated by 3.run-biobombe/6.extract_trained_gene_order.ipynb and
    committed alongside the saved models it describes. That notebook derives
    gene order the same way 3.run-biobombe's own scripts (e.g.
    4.compare_model_weights_cka.py) do: via
    `load_train_test_data(data_directory, train_or_test="train")`, the same
    call `1.train_biobombe_ensemble.py` uses to build the array every model
    in the ensemble is actually fit on. The ensemble itself is a downloaded,
    pretrained artifact that won't be retrained, so this ordering won't
    change either; a real saved PCA model is loaded here only to confirm its
    dimensionality still matches, as a sanity check against drift.

    Parameters
    ----------
    model_save_dir : str or pathlib.Path
        Path to 3.run-biobombe/saved_models.

    Returns
    -------
    list of str
        Gene symbol_id values, in the order the ensemble was trained on.
    """
    model_save_dir = pathlib.Path(model_save_dir)
    gene_order_file = model_save_dir.parent / "data" / "trained_gene_order.parquet"
    trained_gene_order = pd.read_parquet(gene_order_file)["symbol_id"].tolist()

    pca_models = sorted(model_save_dir.glob("pca_*.joblib"))
    if not pca_models:
        raise FileNotFoundError(
            f"No pca_*.joblib model found in {model_save_dir} to sanity-check the gene order against."
        )
    pca_model = joblib.load(pca_models[0])
    if pca_model.n_features_in_ != len(trained_gene_order):
        raise ValueError(
            f"{pca_models[0].name} expects {pca_model.n_features_in_} genes, but "
            f"{gene_order_file} lists {len(trained_gene_order)}. "
            "trained_gene_order.parquet is stale; regenerate it with "
            "3.run-biobombe/6.extract_trained_gene_order.ipynb."
        )

    return trained_gene_order


def load_new_dependency_data(path, sample_id_column=None):
    """
    Load a new gene dependency dataset from parquet or csv.

    Parameters
    ----------
    path : str or pathlib.Path
        Path to the new data file.
    sample_id_column : str, optional
        Name of the column holding sample identifiers. If not given, the
        first non-numeric-looking column is assumed to be the sample id,
        matching how DepMap's own files are structured (ModelID first).

    Returns
    -------
    pd.DataFrame
        The new data with its sample id column renamed to "ModelID", for
        consistency with every other sample-labeled table in this project.
    """
    path = pathlib.Path(path)
    if path.suffix == ".csv":
        new_df = pd.read_csv(path)
    else:
        new_df = pd.read_parquet(path)

    if sample_id_column is None:
        sample_id_column = new_df.columns[0]

    return new_df.rename(columns={sample_id_column: "ModelID"})


def _resolve_new_data_entrez_ids(new_gene_columns, gene_dict_df, gene_id_format="auto"):
    """
    Map new data's gene columns to entrez ids, trying a few common formats.

    Parameters
    ----------
    new_gene_columns : list of str
        The new dataset's gene column names (everything except ModelID).
    gene_dict_df : pd.DataFrame
        The full gene dictionary, used to resolve plain gene symbols.
    gene_id_format : {"auto", "depmap", "symbol", "entrez"}
        "depmap" assumes "SYMBOL (ENTREZID)" columns like DepMap's own files.
        "symbol" assumes bare gene symbols (e.g. "TP53").
        "entrez" assumes bare entrez ids (e.g. "7157").
        "auto" inspects the first column and picks whichever of the above fits.

    Returns
    -------
    dict
        Maps each input column name to its resolved entrez id (str), or to
        None if it couldn't be resolved under the chosen format.
    """
    if gene_id_format == "auto":
        sample_col = str(new_gene_columns[0])
        if _entrez_from_depmap_column(sample_col) is not None:
            gene_id_format = "depmap"
        elif sample_col.strip().isdigit():
            gene_id_format = "entrez"
        else:
            gene_id_format = "symbol"

    symbol_to_entrez = dict(zip(gene_dict_df["symbol_id"], gene_dict_df["entrez_id"]))

    resolved = {}
    for column in new_gene_columns:
        if gene_id_format == "depmap":
            resolved[column] = _entrez_from_depmap_column(column)
        elif gene_id_format == "entrez":
            stripped = str(column).strip()
            resolved[column] = stripped if stripped.isdigit() else None
        elif gene_id_format == "symbol":
            resolved[column] = symbol_to_entrez.get(str(column).strip())
        else:
            raise ValueError(f"Unknown gene_id_format: {gene_id_format}")

    return resolved


def assess_gene_overlap(new_df, depmap_df, gene_dict_df, trained_gene_order, gene_id_format="auto"):
    """
    Report how well a new dataset's genes line up with DepMap and the trained ensemble.

    This is deliberately a report, not a silent alignment: any join between
    new data and the trained models has to go through this first so missing
    or unresolved genes are visible before they can bias a latent score.

    Parameters
    ----------
    new_df : pd.DataFrame
        Output of load_new_dependency_data (has a "ModelID" column).
    depmap_df : pd.DataFrame
        Output of load_depmap_reference's depmap_df.
    gene_dict_df : pd.DataFrame
        Output of load_depmap_reference's gene_dict_df.
    trained_gene_order : list of str
        Output of get_trained_gene_order.
    gene_id_format : str
        Passed through to _resolve_new_data_entrez_ids.

    Returns
    -------
    dict with keys:
        entrez_map : dict, new-data column -> resolved entrez id (or None)
        unresolved_columns : list of new-data columns that couldn't be mapped
        n_new_genes : total gene columns in the new data
        n_resolved : how many were mapped to an entrez id
        depmap_entrez_ids : set of entrez ids covered by CRISPRGeneEffect.csv
        trained_entrez_ids : set of entrez ids the ensemble was trained on
        n_shared_with_depmap : overlap between resolved new-data genes and DepMap
        n_shared_with_trained : overlap between resolved new-data genes and the
            trained gene set
        trained_genes_missing_in_new : trained genes with no match in new data
        is_order_aligned : True if the new data's resolvable genes already
            appear in the same relative order DepMap uses (informational only,
            since every format_* function reorders explicitly regardless)
    """
    new_gene_columns = [c for c in new_df.columns if c != "ModelID"]
    entrez_map = _resolve_new_data_entrez_ids(new_gene_columns, gene_dict_df, gene_id_format)
    unresolved_columns = [c for c, e in entrez_map.items() if e is None]
    resolved_entrez_ids = {e for e in entrez_map.values() if e is not None}

    depmap_entrez_ids = {
        _entrez_from_depmap_column(c) for c in depmap_df.columns if c != "ModelID"
    }
    depmap_entrez_ids.discard(None)

    trained_gene_to_entrez = dict(zip(gene_dict_df["symbol_id"], gene_dict_df["entrez_id"]))
    trained_entrez_ids = {
        trained_gene_to_entrez[g] for g in trained_gene_order if g in trained_gene_to_entrez
    }

    trained_genes_missing_in_new = [
        g for g in trained_gene_order
        if trained_gene_to_entrez.get(g) not in resolved_entrez_ids
    ]

    resolved_in_order = [e for e in entrez_map.values() if e is not None]
    depmap_order = [
        e for e in (_entrez_from_depmap_column(c) for c in depmap_df.columns) if e in resolved_entrez_ids
    ]
    is_order_aligned = resolved_in_order == depmap_order

    return {
        "entrez_map": entrez_map,
        "unresolved_columns": unresolved_columns,
        "n_new_genes": len(new_gene_columns),
        "n_resolved": len(new_gene_columns) - len(unresolved_columns),
        "depmap_entrez_ids": depmap_entrez_ids,
        "trained_entrez_ids": trained_entrez_ids,
        "n_shared_with_depmap": len(resolved_entrez_ids & depmap_entrez_ids),
        "n_shared_with_trained": len(resolved_entrez_ids & trained_entrez_ids),
        "trained_genes_missing_in_new": trained_genes_missing_in_new,
        "is_order_aligned": is_order_aligned,
    }


def format_to_depmap_genes(new_df, depmap_df, overlap_report):
    """
    Reindex new data to DepMap's full gene set and column order.

    Genes DepMap has that the new data doesn't are filled with NaN.
    Genes the new data has that aren't in DepMap are dropped (they can't be
    compared against anything DepMap-derived anyway).

    Returns
    -------
    pd.DataFrame
        ModelID + DepMap's gene columns (DepMap's own "SYMBOL (ENTREZID)"
        labels and order), values from new_df where a gene was resolved.
    """
    entrez_to_new_column = {
        e: c for c, e in overlap_report["entrez_map"].items() if e is not None
    }
    depmap_gene_columns = [c for c in depmap_df.columns if c != "ModelID"]

    aligned = pd.DataFrame(index=new_df.index)
    for depmap_column in depmap_gene_columns:
        entrez_id = _entrez_from_depmap_column(depmap_column)
        source_column = entrez_to_new_column.get(entrez_id)
        aligned[depmap_column] = new_df[source_column] if source_column is not None else np.nan

    aligned.insert(0, "ModelID", new_df["ModelID"].values)
    return aligned


def format_to_trained_gene_order(new_df, gene_dict_df, trained_gene_order, overlap_report):
    """
    Reindex new data to exactly the genes and order the trained ensemble expects.

    Missing genes are filled with NaN here (not imputed) so the caller can
    decide how to handle them explicitly; scale_new_data does the actual
    imputation using the persisted training means.

    Returns
    -------
    pd.DataFrame
        ModelID + trained_gene_order columns, in that exact order.
    """
    entrez_to_new_column = {
        e: c for c, e in overlap_report["entrez_map"].items() if e is not None
    }
    gene_to_entrez = dict(zip(gene_dict_df["symbol_id"], gene_dict_df["entrez_id"]))

    aligned = pd.DataFrame(index=new_df.index)
    for gene in trained_gene_order:
        entrez_id = gene_to_entrez.get(gene)
        source_column = entrez_to_new_column.get(entrez_id)
        aligned[gene] = new_df[source_column] if source_column is not None else np.nan

    aligned.insert(0, "ModelID", new_df["ModelID"].values)
    return aligned


def fit_and_persist_scaler(data_directory, trained_gene_order, output_path):
    """
    Fit a MinMaxScaler on the original training data and persist it, alongside
    the per-gene training means used to impute genes missing from new data.

    This must be fit on the same data the ensemble was trained on, not on any
    new dataset: scaling relative to a different cohort would make latent
    scores incomparable to the ones the models actually learned to produce.

    Parameters
    ----------
    data_directory : str or pathlib.Path
        Path to 0.data-download/data.
    trained_gene_order : list of str
        Output of get_trained_gene_order; fixes both which genes are scaled
        and the column order the scaler's indices correspond to.
    output_path : str or pathlib.Path
        Where to joblib.dump the resulting bundle.

    Returns
    -------
    dict with keys "scaler", "gene_order", "gene_means" (the last two are also
    persisted so a caller only needs to load output_path later, not recompute
    trained_gene_order or re-derive means separately).
    """
    depmap_df, gene_dict_df = load_depmap_reference(data_directory)

    entrez_to_depmap_column = {
        _entrez_from_depmap_column(c): c for c in depmap_df.columns if c != "ModelID"
    }
    gene_to_entrez = dict(zip(gene_dict_df["symbol_id"], gene_dict_df["entrez_id"]))

    training_df = pd.DataFrame(index=depmap_df.index)
    for gene in trained_gene_order:
        depmap_column = entrez_to_depmap_column.get(gene_to_entrez.get(gene))
        training_df[gene] = depmap_df[depmap_column] if depmap_column is not None else np.nan

    gene_means = training_df.mean(axis=0, skipna=True)
    training_df = training_df.fillna(gene_means)

    scaler = MinMaxScaler()
    scaler.fit(training_df.values.astype(np.float32))

    bundle = {"scaler": scaler, "gene_order": trained_gene_order, "gene_means": gene_means}

    output_path = pathlib.Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(bundle, output_path)

    return bundle


def get_or_create_scaler(data_directory, trained_gene_order, output_path):
    """
    Load the persisted scaler bundle if it exists, otherwise fit and persist one.
    """
    output_path = pathlib.Path(output_path)
    if output_path.exists():
        return joblib.load(output_path)
    return fit_and_persist_scaler(data_directory, trained_gene_order, output_path)


def scale_new_data(model_ready_df, scaler_bundle):
    """
    Impute missing genes with training means, then apply the persisted scaler.

    Parameters
    ----------
    model_ready_df : pd.DataFrame
        Output of format_to_trained_gene_order (ModelID + trained_gene_order
        columns, possibly containing NaN for unresolved genes).
    scaler_bundle : dict
        Output of fit_and_persist_scaler / get_or_create_scaler.

    Returns
    -------
    pd.DataFrame
        ModelID + scaled gene columns, same column order as scaler_bundle["gene_order"].
        No NaNs remain.
    """
    gene_order = scaler_bundle["gene_order"]
    gene_means = scaler_bundle["gene_means"]
    scaler = scaler_bundle["scaler"]

    values_df = model_ready_df[gene_order].astype(float)
    n_imputed_per_gene = values_df.isna().sum()
    values_df = values_df.fillna(gene_means)

    scaled = scaler.transform(values_df.values.astype(np.float32))
    scaled_df = pd.DataFrame(scaled, columns=gene_order, index=model_ready_df.index)
    scaled_df.insert(0, "ModelID", model_ready_df["ModelID"].values)

    scaled_df.attrs["n_imputed_per_gene"] = n_imputed_per_gene
    return scaled_df


def scale_depmap_reference(depmap_df, gene_dict_df, scaler_bundle):
    """
    Format and scale the original DepMap data the same way new data is scaled,
    so the two are comparable in step 3's distribution checks.

    Unlike scale_new_data, this doesn't need gene-id resolution: depmap_df is
    the same data the scaler's training means and MinMaxScaler came from, so
    every trained gene is present by construction.

    Returns
    -------
    pd.DataFrame
        ModelID + scaled gene columns, same column order as scaler_bundle["gene_order"].
    """
    gene_order = scaler_bundle["gene_order"]
    gene_to_entrez = dict(zip(gene_dict_df["symbol_id"], gene_dict_df["entrez_id"]))
    entrez_to_depmap_column = {
        _entrez_from_depmap_column(c): c for c in depmap_df.columns if c != "ModelID"
    }

    aligned = pd.DataFrame(index=depmap_df.index)
    for gene in gene_order:
        depmap_column = entrez_to_depmap_column.get(gene_to_entrez.get(gene))
        aligned[gene] = depmap_df[depmap_column] if depmap_column is not None else np.nan
    aligned.insert(0, "ModelID", depmap_df["ModelID"].values)

    return scale_new_data(aligned, scaler_bundle)


def prepare_new_data_for_biobombe(
    new_data_path,
    data_directory,
    model_save_dir,
    scaler_path,
    sample_id_column=None,
    gene_id_format="auto",
):
    """
    End-to-end: load new data and return everything needed to run it through
    the BioBombe ensemble, in one call.

    This is the convenience function referenced in this module's README —
    load, assess overlap, format both ways, and scale, using (and creating,
    if it doesn't exist yet) the persisted training scaler.

    Returns
    -------
    dict with keys:
        raw : the loaded new data, unmodified except for the ModelID rename
        overlap_report : output of assess_gene_overlap
        depmap_aligned : output of format_to_depmap_genes
        model_ready_scaled : output of scale_new_data, ready to feed straight
            into each saved model's .transform()/.encode()
        scaler_bundle : the scaler bundle used
    """
    depmap_df, gene_dict_df = load_depmap_reference(data_directory)
    trained_gene_order = get_trained_gene_order(data_directory, model_save_dir)

    raw = load_new_dependency_data(new_data_path, sample_id_column=sample_id_column)
    overlap_report = assess_gene_overlap(
        raw, depmap_df, gene_dict_df, trained_gene_order, gene_id_format=gene_id_format
    )

    depmap_aligned = format_to_depmap_genes(raw, depmap_df, overlap_report)
    model_ready = format_to_trained_gene_order(raw, gene_dict_df, trained_gene_order, overlap_report)

    scaler_bundle = get_or_create_scaler(data_directory, trained_gene_order, scaler_path)
    model_ready_scaled = scale_new_data(model_ready, scaler_bundle)

    return {
        "raw": raw,
        "overlap_report": overlap_report,
        "depmap_aligned": depmap_aligned,
        "model_ready_scaled": model_ready_scaled,
        "scaler_bundle": scaler_bundle,
    }
